import type { FormEvent } from 'react'
import type { CustomerFlowSnapshot, CustomerPayment } from '../../contracts/domain-contracts'
import type { FinanceCategory, FinancialAccount } from '../../erp-types'
import { customerForm, money, shortDate } from './customer-workspace-utils'

export function CustomerEditForm({ snapshot, working, onSubmit }: { snapshot: CustomerFlowSnapshot; working: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const form = customerForm(snapshot)
  return <form className="erp-form" onSubmit={onSubmit}><div className="erp-form-grid">
    <label><span>Full name</span><input name="full_name" defaultValue={form.full_name} required /></label><label><span>Customer type</span><select name="customer_type" defaultValue={form.customer_type}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="society">Society</option><option value="institutional">Institutional</option></select></label>
    <label><span>Phone</span><input name="phone" defaultValue={form.phone} required /></label><label><span>Alternate phone</span><input name="alternate_phone" defaultValue={form.alternate_phone} /></label>
    <label><span>Email</span><input name="email" type="email" defaultValue={form.email} /></label><label><span>Consumer number</span><input name="consumer_number" defaultValue={form.consumer_number} /></label>
    <label><span>Electricity provider</span><input name="electricity_provider" defaultValue={form.electricity_provider} /></label><label><span>Lead source</span><input name="lead_source" defaultValue={form.lead_source} /></label>
    <label className="erp-form-wide"><span>Installation site</span><textarea name="site_address" defaultValue={form.site_address} /></label><label className="erp-form-wide"><span>Billing address</span><textarea name="billing_address" defaultValue={form.billing_address} /></label>
    <label><span>District</span><input name="district" defaultValue={form.district} /></label><label><span>State</span><input name="state" defaultValue={form.state} /></label><label><span>Postal code</span><input name="postal_code" defaultValue={form.postal_code} /></label><label><span>Status</span><select name="status" defaultValue={form.status}><option value="lead">Lead</option><option value="registered">Registered</option><option value="quotation_requested">Quotation requested</option><option value="active">Active</option><option value="on_hold">On hold</option></select></label>
  </div><footer className="erp-form-actions"><button type="submit" className="primary-button" disabled={working}>Save customer</button></footer></form>
}

export function PaymentForm({ accounts, categories, payment, working, onSubmit }: { accounts: FinancialAccount[]; categories: FinanceCategory[]; payment?: CustomerPayment | null; working: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  if (payment) {
    return <form className="erp-form" onSubmit={onSubmit}>
      <div className="customer-lifecycle-impact"><strong>Saved transaction</strong><p>{payment.transaction_number} · {shortDate.format(new Date(payment.transaction_date))} · {payment.direction === 'credit' ? 'Money in' : 'Money out'} · {money.format(Number(payment.amount))}</p><p>To change the amount, account, date, type, or direction, reverse this transaction.</p></div>
      <input type="hidden" name="transaction_date" value={payment.transaction_date} /><input type="hidden" name="direction" value={payment.direction} /><input type="hidden" name="amount" value={payment.amount} /><input type="hidden" name="account_id" value={payment.account_id} /><input type="hidden" name="category_id" value={payment.category_id || ''} /><input type="hidden" name="source_type" value={payment.source_type} />
      <div className="erp-form-grid"><label><span>Payment method</span><select name="payment_method" defaultValue={payment.payment_method || 'bank'}><option value="bank">Bank</option><option value="cash">Cash</option><option value="upi">UPI</option><option value="cheque">Cheque</option></select></label><label><span>Reference</span><input name="reference_number" defaultValue={payment.reference_number} /></label><label className="erp-form-wide"><span>Description</span><input name="description" defaultValue={payment.description} placeholder="Short payment note" /></label></div>
      <footer className="erp-form-actions"><button className="primary-button" disabled={working}>Save changes</button></footer>
    </form>
  }
  return <form className="erp-form" onSubmit={onSubmit}><div className="erp-form-grid"><label><span>Date</span><input type="date" name="transaction_date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label><span>Direction</span><select name="direction" defaultValue="credit"><option value="credit">Money in</option><option value="debit">Refund / money out</option></select></label><label><span>Amount</span><input type="number" min="0.01" step="0.01" name="amount" required /></label><label><span>Account</span><select name="account_id" defaultValue="" required><option value="">Select account</option>{accounts.map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label><span>Category</span><select name="category_id" defaultValue=""><option value="">No category</option>{categories.map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label><span>Payment method</span><select name="payment_method" defaultValue="bank"><option value="bank">Bank</option><option value="cash">Cash</option><option value="upi">UPI</option><option value="cheque">Cheque</option></select></label><label><span>Type</span><select name="source_type" defaultValue="customer_payment"><option value="customer_payment">Customer payment</option><option value="customer_advance">Advance</option><option value="loan_disbursement">Loan payout</option><option value="subsidy_received">Subsidy received</option><option value="customer_refund">Refund</option></select></label><label><span>Reference</span><input name="reference_number" /></label><label className="erp-form-wide"><span>Description</span><input name="description" placeholder="Short payment note" /></label></div><footer className="erp-form-actions"><button className="primary-button" disabled={working || !accounts.length}>Save transaction</button></footer></form>
}

export function LoanForm({ snapshot, working, onSubmit }: { snapshot: CustomerFlowSnapshot; working: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const loan = snapshot.loan
  return <form className="erp-form" onSubmit={onSubmit}><div className="erp-form-grid"><label><span>Bank</span><input name="bank_name" defaultValue={loan?.bank_name} /></label><label><span>Application number</span><input name="application_number" defaultValue={loan?.application_number} /></label><label><span>Requested amount</span><input type="number" name="requested_amount" defaultValue={loan?.requested_amount ?? 0} /></label><label><span>Approved amount</span><input type="number" name="approved_amount" defaultValue={loan?.approved_amount ?? 0} /></label><label><span>Customer share</span><input type="number" name="customer_contribution" defaultValue={loan?.customer_contribution ?? 0} /></label><label><span>Application status</span><select name="application_status" defaultValue={loan?.application_status ?? 'draft'}>{['draft','applied','documents_pending','submitted_to_bank','under_review','conditionally_approved','approved','rejected','cancelled'].map((row) => <option key={row}>{row}</option>)}</select></label><label><span>Document status</span><select name="documentation_status" defaultValue={loan?.documentation_status ?? 'pending'}><option>pending</option><option>submitted</option><option>approved</option><option>rejected</option></select></label><label><span>Loan status</span><select name="loan_status" defaultValue={loan?.loan_status ?? 'draft'}>{['draft','applied','documents_pending','submitted_to_bank','under_review','conditionally_approved','approved','partially_disbursed','fully_disbursed','rejected','cancelled'].map((row) => <option key={row}>{row}</option>)}</select></label><label><span>First payout</span><input type="number" name="first_disbursement_amount" defaultValue={loan?.first_disbursement_amount ?? 0} /></label><label><span>Second payout</span><input type="number" name="second_disbursement_amount" defaultValue={loan?.second_disbursement_amount ?? 0} /></label><label><span>EMI amount</span><input type="number" name="emi_amount" defaultValue={loan?.emi_amount ?? 0} /></label><label className="erp-form-wide"><span>Note</span><textarea name="note" defaultValue={loan?.note} /></label></div><footer className="erp-form-actions"><button className="primary-button" disabled={working}>Save loan</button></footer></form>
}

export function SalesBillForm({ approvedValue, working, onSubmit }: { approvedValue: number; working: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const today = new Date().toISOString().slice(0, 10)
  return <form className="erp-form" onSubmit={onSubmit}><div className="erp-form-grid"><label><span>Bill number</span><input name="bill_number" required /></label><label><span>Bill date</span><input type="date" name="bill_date" defaultValue={today} required /></label><label><span>Due date</span><input type="date" name="due_date" /></label><label><span>Subtotal</span><input type="number" name="subtotal" min="0" step="0.01" defaultValue={approvedValue} required /></label><label><span>Tax</span><input type="number" name="tax_amount" min="0" step="0.01" defaultValue="0" /></label><label className="erp-form-wide"><span>Note</span><textarea name="note" /></label></div><footer className="erp-form-actions"><button className="primary-button" disabled={working}>Create sales bill</button></footer></form>
}
