import type { WorkflowQuotation } from '../types'
import {
  buildPdfBlobFromStreams,
  DocumentPackPdfLayout,
  PDF_CONTENT_WIDTH,
  PDF_LIGHT_BLUE,
  PDF_NAVY,
  pdfMoney,
} from './document-pack/pdf'
import { defaultDocumentPackTemplate } from './document-pack/template'
import type { DocumentPackInput, DocumentPackTemplate } from './document-pack/types'
import { loadCustomerSignature, type PdfSignatureImage } from './document-pack/signature'

export type QuotationDocumentData = {
  quotation: WorkflowQuotation
  customerName: string
  companyName?: string
  phone?: string
  email?: string
  address?: string
  siteAddress?: string
  capacityKw?: number
  notes?: string
  agentName?: string
  customerId?: string
  customerSignature?: PdfSignatureImage
}

const money = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR',
  maximumFractionDigits: 2,
})

const date = new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' })

export function formatQuotationMoney(value: number) {
  return money.format(Number(value || 0))
}

export function quotationFileName(quotationNumber: string) {
  const safeNumber = quotationNumber.replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '')
  return `${safeNumber || 'quotation'}.pdf`
}

function displayDate(value: string | null | undefined) {
  if (!value) return 'Not specified'
  const parsed = new Date(value)
  return Number.isNaN(parsed.getTime()) ? value : date.format(parsed)
}

function validityDays(quotation: WorkflowQuotation) {
  if (!quotation.valid_until) return '15'
  const created = new Date(quotation.created_at).getTime()
  const validUntil = new Date(quotation.valid_until).getTime()
  if (!Number.isFinite(created) || !Number.isFinite(validUntil)) return '15'
  return String(Math.max(1, Math.ceil((validUntil - created) / 86_400_000)))
}

function layoutInput(data: QuotationDocumentData): DocumentPackInput {
  const { quotation } = data
  return {
    customerName: data.customerName,
    customerNumber: '',
    projectNumber: quotation.quotation_number,
    quotationNumber: quotation.quotation_number,
    address: data.siteAddress || data.address || '',
    district: '',
    consumerNumber: '',
    customerCategory: data.companyName || 'Individual customer',
    plantCapacity: String(data.capacityKw || ''),
    quotationAmount: String(quotation.grand_total || ''),
    panelSize: '',
    numberOfPanels: '',
    panelBrand: '',
    inverterBrand: '',
    structureType: '',
    cableBrand: '',
    salesPerson: data.agentName || '',
    agreementDate: quotation.created_at.slice(0, 10),
    validityDays: validityDays(quotation),
    notes: data.notes || '',
  }
}

function layoutTemplate(data: QuotationDocumentData): DocumentPackTemplate {
  return {
    ...defaultDocumentPackTemplate,
    company_name: 'Shree EnterPrise',
    brand_name: 'Perfect Solar',
    quotation_title: 'Approved Solar Quotation',
    footer: 'Approved quotation generated by the system',
    vendor_signatory_name: data.agentName || 'Authorized signatory',
    vendor_signatory_title: data.agentName ? 'Sales representative' : 'Authorized signatory',
  }
}

export function createQuotationPdf(data: QuotationDocumentData) {
  if (data.quotation.status !== 'approved' || !data.customerSignature) return null

  const { quotation } = data
  const input = layoutInput(data)
  const layout = new DocumentPackPdfLayout(input, layoutTemplate(data), data.customerSignature)
  const lines = quotation.lines.length > 0 ? quotation.lines : [{
    description: quotation.title,
    quantity: 1,
    unit: 'Lot',
    unit_price: quotation.subtotal,
    tax_rate: quotation.subtotal > 0 ? (quotation.tax_total / quotation.subtotal) * 100 : 0,
    line_total: quotation.grand_total,
  }]

  layout.beginDocument('Approved Solar Quotation', quotation.title)
  layout.note(`APPROVED${quotation.approved_at ? ` on ${displayDate(quotation.approved_at)}` : ''}${quotation.decision_comment ? ` - ${quotation.decision_comment}` : ''}`)
  layout.section('Customer & Quotation Details')
  layout.kvTable([
    ['Quotation Number', quotation.quotation_number],
    ['Customer', data.customerName],
    ['Customer Company', data.companyName || 'Individual customer'],
    ['Phone / Email', [data.phone, data.email].filter(Boolean).join(' | ') || '-'],
    ['Installation Site', data.siteAddress || data.address || '-'],
    ['Proposed Capacity', data.capacityKw ? `${data.capacityKw} kW` : '-'],
    ['Created', displayDate(quotation.created_at)],
    ['Valid Until', displayDate(quotation.valid_until)],
  ])

  layout.section('Approved Line Items')
  layout.table(
    [{ text: '#' }, { text: 'Description' }, { text: 'Qty' }, { text: 'Rate' }, { text: 'Tax' }, { text: 'Amount' }],
    lines.map((item, index) => [
      { text: String(index + 1), align: 'center' },
      { text: item.description },
      { text: `${item.quantity} ${item.unit}`, align: 'center' },
      { text: pdfMoney(item.unit_price), align: 'right' },
      { text: `${item.tax_rate}%`, align: 'right' },
      { text: pdfMoney(item.line_total), bold: true, align: 'right' },
    ]),
    [24, 220, 54, 75, 53, PDF_CONTENT_WIDTH - 426],
    { fontSize: 7.1, padding: 4, headerFontSize: 6.9 },
  )

  layout.section('Approved Totals')
  layout.table(null, [
    [{ text: 'Subtotal', bold: true, fill: PDF_LIGHT_BLUE }, { text: pdfMoney(quotation.subtotal), bold: true, align: 'right' }],
    [{ text: 'Tax', bold: true, fill: PDF_LIGHT_BLUE }, { text: pdfMoney(quotation.tax_total), bold: true, align: 'right' }],
    [{ text: 'Grand Total', bold: true, fill: PDF_NAVY, color: '#ffffff' }, { text: pdfMoney(quotation.grand_total), bold: true, fill: PDF_NAVY, color: '#ffffff', align: 'right' }],
  ], [PDF_CONTENT_WIDTH - 150, 150], { fontSize: 8.5, padding: 5 })

  if (data.notes) layout.note(data.notes)
  if (data.agentName) layout.paragraph(`Prepared by: ${data.agentName}`, { bold: true, fontSize: 8 })
  layout.signatures()

  return buildPdfBlobFromStreams(layout.finish(), 'ERP-APPROVED-QUOTATION', data.customerSignature)
}

export async function downloadQuotationPdf(data: QuotationDocumentData) {
  const loaded = !data.customerSignature && data.customerId
    ? await loadCustomerSignature(data.customerId)
    : null
  const blob = createQuotationPdf({ ...data, customerSignature: data.customerSignature || loaded?.pdf })
  if (!blob) return false
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = quotationFileName(data.quotation.quotation_number)
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  return true
}
